# Generated by Django 3.0.3 on 2020-03-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200317_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='score',
        ),
    ]
