# Generated by Django 3.0.3 on 2020-03-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_teacher_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='deliverby',
        ),
        migrations.AddField(
            model_name='rank',
            name='year',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rank',
            name='teacher',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
