# Generated by Django 3.0.3 on 2020-03-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200317_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='teacher',
            new_name='teacherid',
        ),
    ]
