# Generated by Django 3.0.3 on 2020-03-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rank_teachername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='teachername',
        ),
    ]
