# Generated by Django 3.0.3 on 2020-03-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_rank_teachername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
